products = [
    {
      '_id': '1',
      'name': 'Essence tribulus terrestris',
      'image': '/images/pit0.jpg',
      'description':
        'Essence tribulus terrestris is an excellent choice for people who want to improve their overall wellbeing and enhance their athletic performance. This product is made from high-quality ingredients and is free of harmful additives.',
      'brand': 'Essence',
      'category': 'Food Supplement',
      'price': 25.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'OstroVit Fat Burner eXtreme',
      'image': '/images/pit1.png',
      'description':
        'OstroVit Fat Burner eXtreme is a highly effective food supplement designed to support weight loss and help you reach your fitness goals. This product contains a powerful blend of ingredients that work together to boost your metabolism, increase energy levels, and promote fat burning.',
      'brand': 'OstroVit',
      'category': 'Food Supplement',
      'price': 32.99,
      'countInStock': 7,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Muscle Up ActivLab',
      'image': '/images/pit2.jpg',
      'description':
        'Muscle Up ActivLab is a powerful pre-workout supplement designed to help boost your energy, improve your performance, and maximize your results. This supplement contains a highly concentrated formula of ingredients that help to promote muscle growth and support physical endurance during training.',
      'brand': 'Muscle Up',
      'category': 'Protein',
      'price': 74.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Whey protein ALL Nutrition',
      'image': '/images/pit3.jpg',
      'description':
        'Incorporating Whey protein ALL Nutrition into your diet can help you support your fitness goals. Whether you are trying to build muscle or maintain a healthy lifestyle, this supplement is a great choice to help you achieve your goals faster and more efficiently.',
      'brand': 'All Nutrition',
      'category': 'Protein',
      'price': 89.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'C 1000 NaturalSupp',
      'image': '/images/pit4.png',
      'description':
        'This product is made from high-quality ingredients and is free of any harmful additives, making it safe and effective to use. It has been rigorously tested and manufactured according to strict quality standards, ensuring purity, and efficacy.',
      'brand': 'NaturalSupp',
      'category': 'Vitamins',
      'price': 24.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'COENZYME Q10',
      'image': '/images/pit5.jpg',
      'description':
        'Coenzyme Q10, or CoQ10, is a powerful antioxidant and essential nutrient that plays a vital role in energy production, heart health, and overall wellbeing. CoQ10 is naturally produced in our bodies, but as we age, our natural production of this coenzyme declines, and we may start to experience symptoms of deficiency.',
      'brand': 'Coenzyme',
      'category': 'Vitamins',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  ]
  