# Generated by Django 4.2.2 on 2023-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='id',
        ),
        migrations.AddField(
            model_name='promocode',
            name='_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
