# Generated by Django 4.2.2 on 2023-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_promocode_id_promocode__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='_id',
        ),
        migrations.AddField(
            model_name='promocode',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
