# Generated by Django 4.2.2 on 2023-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_promocode__id_promocode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountProduct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
