# Generated by Django 4.2.2 on 2023-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/nutrinationcloud.appspot.com/o/images%2Fplaceholder.png?alt=media&token=d31420b6-5295-42e9-8f99-8c39a5860a72', max_length=255, null=True, upload_to=''),
        ),
    ]
